# This workflow will perform a build of the project and run tests

name: Build and check

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  # Allows to run from the Actions tab
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    uses: centic9/actions/.github/workflows/gradle-build.yml@6
